spring:
  application:
     name: welcome
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
    port: 8081
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka/ #optional when use these port, because default is 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"    #actuator endpoints configure
